patrons_site/patrons_app/urls.py
from django.urls import path
from . import views

app_name = 'patrons_app'

urlpatterns = [
    path('register/', views.register,name='register'),
    path('user_login', views.user_login,name='user_login'),
]

patrons_site/patrons_site/urls.py
from django.contrib import admin
from django.urls import path, include
from patrons_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('user_app/', include('patrons_app.urls')),
    path('special/', views.special, name='special'),
    path('logout/', views.logout, name='logout'),
]

patrons_site/patrons_app/models.py
from distutils.command.upload import upload
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    # create relationship (inherit from User)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)
    # pip install pillow to use this
    # optional" pip install pillow --global-option:

    profile_pic = models.ImageField(upload_to='patrons_app/profile_pics', blank=True)

    def __str__(self):
        # built-in attribute of django.contrib.auth.models.User
        return self.user.username

patrons_site/patrons_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

patrons_site/patrons_app/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm

# Extra imports for the lgoin & logout capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    return render(request,'patrons_app/index.html')

# requires user to be loggedin for view
@login_required
def special(request):
    # set login url in settings.py
    # LOGIN_URL = 'patrons_app/user_login'
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # logout the user
    logout(request)
    # REturn to homepage
    return HttpResponseRedirect(reverse('patrons_app/index.html'))

def register(request):
    registered= False
    if request.method=='POST':
        # get info from "both" forms
        # It apprears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        # is valid from dir(forms.ModelForm)
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            # .save() from dir(forms.ModelForm)
            user = user_form.save()

            # hash the password
            # dir(User) is .set_password
            user.set_password(user.password)

            # update with the hashed password
            user.save()

            # now deal with extra info

            # cant commit yet still need to manipulate
            profile = profile_form.save(commit=False)

            # set ONE to ONE relationship between
            # UserFrom and UserProfileInfoForm

            profile.user = user

            # check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic= request.FILES['profile_pic']

            # now save the model
            profile.save()

            # REgistration Successful
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors, profile_form.errors)

    else:
        # was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request, 'patrons_app/registration.html',
    {'user_form':user_form,
    'profile_form': profile_form,
    'registered': registered})

def user_login(request):
    if request.method == 'POST':
        # first get the username and assword supplied
        # get name='' from input tag the template login.html
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            # Check if the acount is active
            if user.is_active:
                # log the user in
                login(request,user)
                # send the user back to some page
                # in this case their homepage
                return HttpResponseRedirect(reverse('index'))
            else:
                # if account is not active:
                return HttpResponse("Your account is not active")
        else:
            print("Someone tried to login and failed")
            print(f'They used username: {username} and password: {password}')
            return HttpResponse("Invalid login details supplied")
    else:
        # Nothing has been provided for username or password
        return render(request, 'patrons_app/login.html', {})

patrons_site/patrons_app/templates/patrons_app/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>TEMPLATES IN BASE_DIR</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
        <nav class="">
            <div class="">
              {# Django Home Link / Admin Link / Register Link#}
              <a class="" href="{% url 'index' %}">DJANGO</a>
              <a class="" href="{% url 'admin:index' %}">Admin</a>
              <a class="" href="{% url 'patrons_app:register' %}">Register</a>
      
              {# Some logic on what to display for last item#}
              {% if user.is_authenticated %}
                <a class="" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="" href="{% url 'patrons_app:user_login' %}">Login</a>
              {% endif %}
            </div>
        </nav>
      
        <div class="container">
          {% block body_block %}
          {% endblock %}
        </div>
        <script src="" async defer></script>
    </body>
</html>

patrons_site/patrons_app/templates/patrons_app/index.html
{% extends "patrons_app/base.html" %}
{% block body_block %}

<div class="container">
  <div class="">
    <h1>Django Level Five</h1>
    {% if user.is_authenticated %}
        <h2>Welcome {{ user.username }}!</h2>
    {% else %}
        <h2>Welcome to the site!</h2>
    {% endif %}
  </div>
</div>

{% endblock %}

patrons_site/patrons_app/templates/patrons_app/login.html
{% extends 'patrons_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>
<!-- user_login from views -->
        <form method="post" action="{% url 'patrons_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Enter Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

patrons_site/patrons_app/templates/patrons_app/registration.html
{% extends "patrons_app/base.html" %}
{% load static %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}

patrons_site/templates/patrons_app/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>TEMPLATES IN BASE_DIR</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
        <nav class="">
            <div class="">
              {# Django Home Link / Admin Link / Register Link#}
              <a class="" href="{% url 'index' %}">DJANGO</a>
              <a class="" href="{% url 'admin:index' %}">Admin</a>
              <a class="" href="{% url 'patrons_app:register' %}">Register</a>
      
              {# Some logic on what to display for last item#}
              {% if user.is_authenticated %}
              <!-- .is_authenticated from dir(User)  -->
                <a class="" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="" href="{% url 'patrons_app:user_login' %}">Login</a>
              {% endif %}
            </div>
        </nav>
      
        <div class="container">
          {% block body_block %}
          {% endblock %}
        </div>
        <script src="" async defer></script>
    </body>
</html>

patrons_site/templates/patrons_app/index.html
{% extends "patrons_app/base.html" %}
{% block body_block %}

<div class="container">
  <div class="">
    <h1>Django Level Five</h1>
    {% if user.is_authenticated %}
        <h2>Welcome {{ user.username }}!</h2>
    {% else %}
        <h2>Welcome to the site!</h2>
    {% endif %}
  </div>
</div>

{% endblock %}

patrons_site/templates/patrons_app/login.html
{% extends 'patrons_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'patrons_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

patrons_site/templates/patrons_app/registration.html
{% extends "patrons_app/base.html" %}
{% load static %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}